export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN = 'SIGN_IN';
export const AUTH_LOADING_START = 'AUTH_LOADING_START';
export const AUTH_LOADING_STOP = 'AUTH_LOADING_STOP';
export const USER_LOADING_START = 'USER_LOADING_START';
export const USER_LOADING_STOP = 'USER_LOADING_STOP';

export const GET_TODOS = 'GET_TODOS';
export const TODOS_LOADING_START = 'TODOS_LOADING_START';
export const TODOS_LOADING_STOP = 'TODOS_LOADING_STOP';
export const ADD_TOKEN = 'ADD_TOKEN';
